FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache git
RUN git init
RUN corepack enable
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc ./
COPY apps/web/package.json ./apps/web/
RUN pnpm install --frozen-lockfile

COPY . .

WORKDIR /app/apps/web

EXPOSE 3000
CMD ["npx", "next", "dev", "-H", "0.0.0.0", "--no-turbopack"]
