FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache git
RUN corepack enable
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc ./
COPY apps/api/package.json ./apps/api/
RUN pnpm install --frozen-lockfile

COPY . .

WORKDIR /app/apps/api

RUN npx prisma generate

EXPOSE 3001
CMD ["sh", "-c", "npx prisma migrate deploy && npx nest start --watch"]
